### PR TITLE
geofile.txt-comma separator

### PR DESCRIPTION
**Pull request by edrakopo**
Adding comma separator to geofile.txt.

### CODE REVIEW

**Comment by edrakopo** [comment]
Adding HitsVisualisation directory

**Comment by P3tru** [comment]
Hi Lilia, 

Thanks again for this feature. Would you mind removing the .ipython checkpoint file ? Afterwards I'll merge the PR.

**Comment by P3tru** [comment]
Thanks Lilia, I played around it's a very nice feature !

**Comment by edrakopo** [comment]
Thanks Stephane. Sorry if my requests are messy, I don't have very much experience with these. I'll keep training though :-)

**Pull request merged**
